//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genesis.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_payment
    {
        public int paymentId { get; set; }
        public Nullable<int> supplierId { get; set; }
        public string referenceNumber { get; set; }
        public Nullable<System.DateTime> paymentDate { get; set; }
        public Nullable<decimal> cashAmount { get; set; }
        public Nullable<decimal> chequeAmount { get; set; }
        public string chequeNumber { get; set; }
        public Nullable<System.DateTime> chequeDate { get; set; }
        public string chequeBank { get; set; }
        public Nullable<decimal> totalPayment { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> dateLastModified { get; set; }
        public Nullable<int> lastModifiedBy { get; set; }
        public Nullable<decimal> runningBalance { get; set; }
        public string TypeOfPayment { get; set; }
        public string ModeOfPayment { get; set; }
    }
}
