//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genesis.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_productCategory
    {
        public int categoryId { get; set; }
        public string categoryCode { get; set; }
        public string categoryName { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<int> createdBy { get; set; }
    }
}
