//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genesis.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_supplier
    {
        public int supplierId { get; set; }
        public string supplierCode { get; set; }
        public string supplierName { get; set; }
        public string supplierAddress { get; set; }
        public string supplierContactNumber { get; set; }
        public string supplierContactPerson { get; set; }
        public Nullable<int> branchId { get; set; }
        public int status { get; set; }
        public System.DateTime dateCreated { get; set; }
        public int createdBy { get; set; }
        public Nullable<System.DateTime> dateLastModified { get; set; }
        public Nullable<int> modifiedBy { get; set; }
    }
}
