//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genesis.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_documentType
    {
        public int documentTypeId { get; set; }
        public string documentTypeName { get; set; }
        public string documentPrefix { get; set; }
        public System.DateTime dateCreated { get; set; }
        public int createdBy { get; set; }
    }
}
