//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genesis.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_users
    {
        public int userId { get; set; }
        public string userName { get; set; }
        public string passWord { get; set; }
        public string emailAddress { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string lastName { get; set; }
        public int branchId { get; set; }
        public Nullable<System.DateTime> dateLastLogin { get; set; }
        public System.DateTime dateCreated { get; set; }
        public Nullable<System.DateTime> dateLastPasswordChange { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> isAdmin { get; set; }
    }
}
