//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genesis.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_client
    {
        public int clientId { get; set; }
        public string clientCode { get; set; }
        public string clientName { get; set; }
        public string clientAddress { get; set; }
        public string clientContactNumber { get; set; }
        public string clientContactPerson { get; set; }
        public Nullable<int> branchId { get; set; }
        public int status { get; set; }
        public System.DateTime dateCreated { get; set; }
        public int createdBy { get; set; }
        public Nullable<System.DateTime> dateLastModified { get; set; }
        public Nullable<int> modifiedBy { get; set; }
    }
}
