//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genesis.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product
    {
        public int productId { get; set; }
        public string productCode { get; set; }
        public string productName { get; set; }
        public string productDescription { get; set; }
        public Nullable<int> categoryId { get; set; }
        public Nullable<int> reorderLevel { get; set; }
        public string UOM { get; set; }
        public Nullable<int> branchId { get; set; }
        public Nullable<decimal> unitPrice { get; set; }
        public Nullable<int> beginning { get; set; }
        public Nullable<int> incoming { get; set; }
        public Nullable<int> outgoing { get; set; }
        public Nullable<int> ending { get; set; }
        public Nullable<int> modifiedBy { get; set; }
        public Nullable<System.DateTime> dateLastModified { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
    }
}
